=== shiliang1027/technology/WebContent/WEB-INF/xsd/module.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--W3C Schema generated by XMLSpy v2006 rel. 3 U (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="id">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="name">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="desc">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="url">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="icon">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="website-module">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="module" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="module">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="id"/>
				<xs:element ref="name"/>
				<xs:element ref="desc"/>
				<xs:element ref="url"/>
				<xs:element ref="icon"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== shiliang1027/technology/WebContent/WEB-INF/config/module.xml
<?xml version="1.0" encoding="UTF-8"?>
<website-module xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/module.xsd">
	<!-- 系统管理 -->
	<module>
		<id>systemManager</id>
		<name>%CF%B5%CD%B3%B9%DC%C0%ED</name>
		<desc>%CF%B5%CD%B3%B9%DC%C0%ED</desc>
		<url></url>
		<icon>systemManagerModule.jpg</icon>
	</module>
	
	<!-- 安全管理 -->
	<module>
		<id>safeManager</id>
		<name>%B0%B2%C8%AB%B9%DC%C0%ED</name>
		<desc>%B0%B2%C8%AB%B9%DC%C0%ED</desc>
		<url></url>
		<icon>safeManagerModule.jpg</icon>
	</module>
	<!-- 菜单管理/menuManager.action -->
	<module>
		<id>menuManager</id>
		<name>%B2%CB%B5%A5%B9%DC%C0%ED</name>
		<desc>%B2%CB%B5%A5%B9%DC%C0%ED</desc>
		<url>/manage/menu.html</url>
		<icon>menuManagerModule.jpg</icon>
	</module>
	
	<!-- 用户管理/userManager.action -->
	<module>
		<id>userManager</id>
		<name>%D3%C3%BB%A7%B9%DC%C0%ED</name>
		<desc>%D3%C3%BB%A7%B9%DC%C0%ED</desc>
		<url>/manage/user.html</url>
		<icon>userManagerModule.jpg</icon>
	</module>
	
	<!-- 角色管理/roleManager.action -->
	<module>
		<id>roleManager</id>
		<name>%BD%C7%C9%AB%B9%DC%C0%ED</name>
		<desc>%BD%C7%C9%AB%B9%DC%C0%ED</desc>
		<url>/manage/role.html</url>
		<icon>roleManagerModule.jpg</icon>
	</module>
	
	<!-- 状态监控 -->
	<module>
		<id>stateMonitor</id>
		<name>%D7%B4%CC%AC%BC%E0%BF%D8</name>
		<desc>%D7%B4%CC%AC%BC%E0%BF%D8</desc>
		<url></url>
		<icon>stateMonitorModule.jpg</icon>
	</module>
	
</website-module>
